import * as turf from '@turf/turf';

export type NysRisDirection = 1 | 2;

export interface NysRoadInventorySystemProperties {
  fid: number;
  region: number;
  gis_id: number;
  dot_id: number;
  direction: NysRisDirection;
  region_co: number;
  fips_co: number;
  county_name: string;
  county: string;
  route: string | null;
  signing: string | null;
  route_no: number | null;
  suffix: string | null;
  co_rd: string | null;
  road_name: string | null;
  begin_description: string | null;
  end_description: string | null;
  county_order: number | null;
  beg_mp: number;
  end_mp: number;
  section_length: number;
  muni_geocode: number | null;
  muni_type: string | null;
  muni_name: string | null;
  jurisdiction: string | null;
  owning_jurisdiction: string | null;
  muni_owner_geocode: number | null;
  muni_owner_type: string | null;
  muni_owner_name: string | null;
  functional_class: number;
  federal_aid_highway__stp_er_: string | null;
  nhs_value: string | null;
  primary: string | null;
  f1991_fed_aid_primary: string | null;
  strahnet: string | null;
  urban_area_code_id: number | null;
  urban_area_name: string | null;
  hpms_ua_code: number | null;
  mpo_desc: string | null;
  overlap_id: string | null;
  overlap_hierarchy: number | null;
  ris_divided_area_id: number | null;
  hpms_sample_id: number | null;
  sh_num: string | null;
  ref_marker: string | null;
  residency: string | null;
  total_lanes: number | null;
  primary_dir_lanes: number | null;
  divided: string | null;
  oneway: string | null;
  access_control: string | null;
  scenic_byway: string | null;
  trail_crossing: string | null;
  toll: string | null;
  toll_facility: string | null;
  parkway: string | null;
  grouped_road_flag: string | null;
  rest_area: string | null;
  discontinuous_road_flag: string | null;
  reservation_desc: string | null;
  tandem_truck: string | null;
  bin_number: string | null;
  bridge_disp_desc: string | null;
  extra_bridges: string | null;
  hov: string | null;
  hov_lanes: number | null;
  railroad_crossing: string | null;
  area: string | null;
  culture: string | null;
  passing: number | null;
  parking: string | null;
  posted_speed_limit: number | null;
  ccstn: number | null;
  station_num: number | null;
  aadt_current_yr_est: number | null;
  aadt_actual: number | null;
  last_actual_cntyr: number | null;
  ddhv: number | null;
  ddhv_factor: number | null;
  adj_cap: number | null;
  v_c: number | null;
  avg_pct_trucks: number | null;
  actual_pct_trucks: number | null;
  actual_pct_year: number | null;
  total_through_lane_width: number | null;
  pavement_type_value: string | null;
  shoulder_width: number | null;
  shoulder_type: string | null;
  median_width: number | null;
  median_type: string | null;
  base: string | null;
  sub_base_type: string | null;
  last_overlay: number | null;
  crack_seal_yr: number | null;
  work_yr: number | null;
  work_type: string | null;
  yr_scored: number | null;
  ss_2007: string | null;
  ss_2008: string | null;
  ss_2009: string | null;
  ss_2010: string | null;
  ss_2011: string | null;
  ss_2012: string | null;
  ss_2013: string | null;
  ss_2014: string | null;
  ss_2015: string | null;
  ss_2016: string | null;
  ss_2017: string | null;
  dom_distr: string | null;
  iri: number | null;
  iri_year: number | null;
  i_rut_depth: number | null;
  rut_year: number | null;
  i_no_of_bumps: number | null;
  bump_cnt_year: number | null;
  max_bump_height: number | null;
  bump_max_year: number | null;
  avg_bump_height: number | null;
  bump_avg_year: number | null;
  pci: number | null;
  roadway_type: string | null;
  onramp_from_roadway: string | null;
  offramp_from_roadway: string | null;
  ramp_interchange_code: string | null;
  ramp_alpha_suffix: string | null;
  ramp_orig_dot_id: string | null;
  ramp_orig_co_order: number | null;
  ramp_orig_mp: number | null;
  ramp_dest_dot_id: string | null;
  ramp_dest_co_order: number | null;
  ramp_dest_mp: number | null;
  segment_type: string | null;
  k_factor: number | null;
  d_factor: number | null;
  percent_peak_single_unit: number | null;
  percent_peak_combp: number | null;
  aadt_single_unit: number | null;
  aadt_combo: number | null;
  pavement_layer: number | null;
  shape_length: number | null;
}

export interface NysRoadInventorySystemFeature
  extends turf.Feature<turf.LineString | turf.MultiLineString> {
  properties: NysRoadInventorySystemProperties;
}
