import * as turf from '@turf/turf';

export type NysRisDirection = 1 | 2;

export interface NysRoadInventorySystemProperties {
  readonly fid: number;
  readonly region: number;
  readonly gis_id: number;
  readonly dot_id: number;
  readonly direction: NysRisDirection;
  readonly region_co: number;
  readonly fips_co: number;
  readonly county_name: string;
  readonly county: string;
  readonly route: string | null;
  readonly signing: string | null;
  readonly route_no: number | null;
  readonly suffix: string | null;
  readonly co_rd: string | null;
  readonly road_name: string | null;
  readonly begin_description: string | null;
  readonly end_description: string | null;
  readonly county_order: number | null;
  readonly beg_mp: number;
  readonly end_mp: number;
  readonly section_length: number;
  readonly muni_geocode: number | null;
  readonly muni_type: string | null;
  readonly muni_name: string | null;
  readonly jurisdiction: string | null;
  readonly owning_jurisdiction: string | null;
  readonly muni_owner_geocode: number | null;
  readonly muni_owner_type: string | null;
  readonly muni_owner_name: string | null;
  readonly functional_class: number;
  readonly federal_aid_highway__stp_er_: string | null;
  readonly nhs_value: string | null;
  readonly primary: string | null;
  readonly f1991_fed_aid_primary: string | null;
  readonly strahnet: string | null;
  readonly urban_area_code_id: number | null;
  readonly urban_area_name: string | null;
  readonly hpms_ua_code: number | null;
  readonly mpo_desc: string | null;
  readonly overlap_id: string | null;
  readonly overlap_hierarchy: number | null;
  readonly ris_divided_area_id: number | null;
  readonly hpms_sample_id: number | null;
  readonly sh_num: string | null;
  readonly ref_marker: string | null;
  readonly residency: string | null;
  readonly total_lanes: number | null;
  readonly primary_dir_lanes: number | null;
  readonly divided: string | null;
  readonly oneway: string | null;
  readonly access_control: string | null;
  readonly scenic_byway: string | null;
  readonly trail_crossing: string | null;
  readonly toll: string | null;
  readonly toll_facility: string | null;
  readonly parkway: string | null;
  readonly grouped_road_flag: string | null;
  readonly rest_area: string | null;
  readonly discontinuous_road_flag: string | null;
  readonly reservation_desc: string | null;
  readonly tandem_truck: string | null;
  readonly bin_number: string | null;
  readonly bridge_disp_desc: string | null;
  readonly extra_bridges: string | null;
  readonly hov: string | null;
  readonly hov_lanes: number | null;
  readonly railroad_crossing: string | null;
  readonly area: string | null;
  readonly culture: string | null;
  readonly passing: number | null;
  readonly parking: string | null;
  readonly posted_speed_limit: number | null;
  readonly ccstn: number | null;
  readonly station_num: number | null;
  readonly aadt_current_yr_est: number | null;
  readonly aadt_actual: number | null;
  readonly last_actual_cntyr: number | null;
  readonly ddhv: number | null;
  readonly ddhv_factor: number | null;
  readonly adj_cap: number | null;
  readonly v_c: number | null;
  readonly avg_pct_trucks: number | null;
  readonly actual_pct_trucks: number | null;
  readonly actual_pct_year: number | null;
  readonly total_through_lane_width: number | null;
  readonly pavement_type_value: string | null;
  readonly shoulder_width: number | null;
  readonly shoulder_type: string | null;
  readonly median_width: number | null;
  readonly median_type: string | null;
  readonly base: string | null;
  readonly sub_base_type: string | null;
  readonly last_overlay: number | null;
  readonly crack_seal_yr: number | null;
  readonly work_yr: number | null;
  readonly work_type: string | null;
  readonly yr_scored: number | null;
  readonly ss_2007: string | null;
  readonly ss_2008: string | null;
  readonly ss_2009: string | null;
  readonly ss_2010: string | null;
  readonly ss_2011: string | null;
  readonly ss_2012: string | null;
  readonly ss_2013: string | null;
  readonly ss_2014: string | null;
  readonly ss_2015: string | null;
  readonly ss_2016: string | null;
  readonly ss_2017: string | null;
  readonly dom_distr: string | null;
  readonly iri: number | null;
  readonly iri_year: number | null;
  readonly i_rut_depth: number | null;
  readonly rut_year: number | null;
  readonly i_no_of_bumps: number | null;
  readonly bump_cnt_year: number | null;
  readonly max_bump_height: number | null;
  readonly bump_max_year: number | null;
  readonly avg_bump_height: number | null;
  readonly bump_avg_year: number | null;
  readonly pci: number | null;
  readonly roadway_type: string | null;
  readonly onramp_from_roadway: string | null;
  readonly offramp_from_roadway: string | null;
  readonly ramp_interchange_code: string | null;
  readonly ramp_alpha_suffix: string | null;
  readonly ramp_orig_dot_id: string | null;
  readonly ramp_orig_co_order: number | null;
  readonly ramp_orig_mp: number | null;
  readonly ramp_dest_dot_id: string | null;
  readonly ramp_dest_co_order: number | null;
  readonly ramp_dest_mp: number | null;
  readonly segment_type: string | null;
  readonly k_factor: number | null;
  readonly d_factor: number | null;
  readonly percent_peak_single_unit: number | null;
  readonly percent_peak_combp: number | null;
  readonly aadt_single_unit: number | null;
  readonly aadt_combo: number | null;
  readonly pavement_layer: number | null;
  readonly shape_length: number | null;
}

export interface NysRoadInventorySystemFeature
  extends turf.Feature<turf.LineString | turf.MultiLineString> {
  properties: NysRoadInventorySystemProperties;
}
