DROP TABLE IF EXISTS __SCHEMA__.nys_ris;

CREATE TABLE __SCHEMA__.nys_ris (
  fid                           INTEGER PRIMARY KEY,
  region                        INTEGER NOT NULL,
  gis_id                        INTEGER NOT NULL,
  dot_id                        INTEGER NOT NULL,
  direction                     INTEGER NOT NULL,
  region_co                     INTEGER NOT NULL,
  fips_co                       INTEGER NOT NULL,
  county_name                   TEXT NOT NULL,
  county                        TEXT NOT NULL,
  route                         TEXT,
  signing                       TEXT,
  route_no                      INTEGER,
  suffix                        TEXT,
  co_rd                         TEXT,
  road_name                     TEXT,
  begin_description             TEXT,
  end_description               TEXT,
  county_order                  INTEGER,
  beg_mp                        REAL NOT NULL,
  end_mp                        REAL NOT NULL,
  section_length                REAL NOT NULL,
  muni_geocode                  INTEGER,
  muni_type                     TEXT,
  muni_name                     TEXT,
  jurisdiction                  TEXT,
  owning_jurisdiction           TEXT,
  muni_owner_geocode            INTEGER,
  muni_owner_type               TEXT,
  muni_owner_name               TEXT,
  functional_class              INTEGER NOT NULL,
  federal_aid_highway__stp_er_  TEXT,
  nhs_value                     TEXT,
  "primary"                     TEXT,
  f1991_fed_aid_primary         TEXT,
  strahnet                      TEXT,
  urban_area_code_id            INTEGER,
  urban_area_name               TEXT,
  hpms_ua_code                  INTEGER,
  mpo_desc                      TEXT,
  overlap_id                    TEXT,
  overlap_hierarchy             INTEGER,
  ris_divided_area_id           INTEGER,
  hpms_sample_id                INTEGER,
  sh_num                        TEXT,
  ref_marker                    TEXT,
  residency                     TEXT,
  total_lanes                   INTEGER,
  primary_dir_lanes             INTEGER,
  divided                       TEXT,
  oneway                        TEXT,
  access_control                TEXT,
  scenic_byway                  TEXT,
  trail_crossing                TEXT,
  toll                          TEXT,
  toll_facility                 TEXT,
  parkway                       TEXT,
  grouped_road_flag             TEXT,
  rest_area                     TEXT,
  discontinuous_road_flag       TEXT,
  reservation_desc              TEXT,
  tandem_truck                  TEXT,
  bin_number                    TEXT,
  bridge_disp_desc              TEXT,
  extra_bridges                 TEXT,
  hov                           TEXT,
  hov_lanes                     INTEGER,
  railroad_crossing             TEXT,
  area                          TEXT,
  culture                       TEXT,
  passing                       INTEGER,
  parking                       TEXT,
  posted_speed_limit            INTEGER,
  ccstn                         INTEGER,
  station_num                   INTEGER,
  aadt_current_yr_est           INTEGER,
  aadt_actual                   INTEGER,
  last_actual_cntyr             INTEGER,
  ddhv                          INTEGER,
  ddhv_factor                   INTEGER,
  adj_cap                       INTEGER,
  v_c                           REAL,
  avg_pct_trucks                INTEGER,
  actual_pct_trucks             INTEGER,
  actual_pct_year               INTEGER,
  total_through_lane_width      REAL,
  pavement_type_value           TEXT,
  shoulder_width                REAL,
  shoulder_type                 TEXT,
  median_width                  INTEGER,
  median_type                   TEXT,
  base                          TEXT,
  sub_base_type                 TEXT,
  last_overlay                  REAL,
  crack_seal_yr                 INTEGER,
  work_yr                       INTEGER,
  work_type                     TEXT,
  yr_scored                     INTEGER,
  ss_2007                       TEXT,
  ss_2008                       TEXT,
  ss_2009                       TEXT,
  ss_2010                       TEXT,
  ss_2011                       TEXT,
  ss_2012                       TEXT,
  ss_2013                       TEXT,
  ss_2014                       TEXT,
  ss_2015                       TEXT,
  ss_2016                       TEXT,
  ss_2017                       TEXT,
  dom_distr                     TEXT,
  iri                           INTEGER,
  iri_year                      INTEGER,
  i_rut_depth                   REAL,
  rut_year                      INTEGER,
  i_no_of_bumps                 INTEGER,
  bump_cnt_year                 INTEGER,
  max_bump_height               REAL,
  bump_max_year                 INTEGER,
  avg_bump_height               REAL,
  bump_avg_year                 INTEGER,
  pci                           INTEGER,
  roadway_type                  TEXT,
  onramp_from_roadway           TEXT,
  offramp_from_roadway          TEXT,
  ramp_interchange_code         TEXT,
  ramp_alpha_suffix             TEXT,
  ramp_orig_dot_id              TEXT,
  ramp_orig_co_order            INTEGER,
  ramp_orig_mp                  REAL,
  ramp_dest_dot_id              TEXT,
  ramp_dest_co_order            INTEGER,
  ramp_dest_mp                  REAL,
  segment_type                  TEXT,
  k_factor                      REAL,
  d_factor                      REAL,
  percent_peak_single_unit      REAL,
  percent_peak_combp            REAL,
  aadt_single_unit              INTEGER,
  aadt_combo                    INTEGER,
  pavement_layer                INTEGER,
  shape_length                  REAL,
  feature                       TEXT,

  UNIQUE (gis_id, beg_mp),
  UNIQUE (gis_id, end_mp),
  CHECK (beg_mp < end_mp),
  CHECK (direction = 1 OR direction = 2),
  CHECK (functional_class IN (1, 2, 4, 6, 7, 8, 9, 11, 12, 14, 16, 17, 18, 19))
) WITHOUT ROWID;

-- Create a spatial index on the geometry
DROP TABLE IF EXISTS __SCHEMA__.nys_ris_geopoly_idx;

CREATE VIRTUAL TABLE __SCHEMA__.nys_ris_geopoly_idx
  USING geopoly(fid) ;
